name: tests:e2e
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Create .env file
        run: |
          touch .env
          echo # DB > .env
          echo DB_HOST=${{ secrets.DB_HOST }} > .env
          echo DB_USER=${{ secrets.DB_USER }} > .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} > .env
          echo DB_PORT=${{ secrets.DB_PORT }} > .env
          echo DB_NAME=${{ secrets.DB_NAME }} > .env

          echo # Auth > .env
          echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} > .env
          echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} > .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} > .env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} > .env
          echo GITHUB_ID=${{ secrets.GITHUB_ID }} > .env
          echo GITHUB_SECRET=${{ secrets.GITHUB_SECRET }} > .env
          source ./.env
      - name: Install Yarn
        run: npm install yarn
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: yarn test:e2e:install
      - name: Run E2E tests
        run: yarn test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
